version: "3"
services:
 web:
  image: hongxingwz/get-started:part2
  deploy:
   replicas: 5
   resources:
    limit:
     cpus: "0.1"
     memory: 50M
   restart_policy:
    condition: on-failure
  ports:
   - "80:80"
  networks:
   - webnet
networks:
 webnet:

